language: cpp
sudo: required
dist: bionic
compiler:
  - clang
os:
  - linux
branches:
  only:
    - master
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode10.1
script:
  - mkdir -p build && cd build && cmake ../ && make && make test